import type { Metadata } from "next";
import {  Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const bengaliSans = Noto_Sans_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bengaliSans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        <main className="flex-1 bg-bgColor">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
